version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-journalsAdmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-JuanRomanRiquelme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - journal-net
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - journal-net
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - journal-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
    - "5601:5601"
    - "8000:8000"
    networks:
      - journal-net
    depends_on:
       - elasticsearch

  website:
    container_name: journals-searcher
    image: colohead3r/journals-searcher:v1-rc06
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:80
      - 5001:443
    networks:
      - journal-net
    restart: unless-stopped

networks:
  journal-net:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    data01: